hiragana = new Vocab("Hiragana", [
    new Letter("a", "あ"),
    new Letter("i", "い"),
    new Letter("u", "う"),
    new Letter("e", "え"),
    new Letter("o", "お"),
    new Letter("ka", "か"),
    new Letter("ki", "き"),
    new Letter("ku", "く"),
    new Letter("ke", "け"),
    new Letter("ko", "こ"),
    new Letter("ga", "が"),
    new Letter("gi", "ぎ"),
    new Letter("gu", "ぐ"),
    new Letter("ge", "げ"),
    new Letter("go", "ご"),
    new Letter("sa", "さ"),
    new Letter("shi", "し"),
    new Letter("su", "す"),
    new Letter("se", "せ"),
    new Letter("so", "そ"),
    new Letter("za", "ざ"),
    new Letter("ji", "じ"),
    new Letter("zu", "ず"),
    new Letter("ze", "ぜ"),
    new Letter("zo", "ぞ"),
    new Letter("ta", "た"),
    new Letter("chi", "ち"),
    new Letter("tsu", "つ"),
    new Letter("te", "て"),
    new Letter("to", "と"),
    new Letter("da", "だ"),
    new Letter("ji", "ぢ"),
    new Letter("zu", "づ"),
    new Letter("de", "で"),
    new Letter("do", "ど"),
    new Letter("na", "な"),
    new Letter("ni", "に"),
    new Letter("nu", "ぬ"),
    new Letter("ne", "ね"),
    new Letter("no", "の"),
    new Letter("ha", "は"),
    new Letter("hi", "ひ"),
    new Letter("fu", "ふ"),
    new Letter("he", "へ"),
    new Letter("ho", "ほ"),
    new Letter("ba", "ば"),
    new Letter("bi", "び"),
    new Letter("bu", "ぶ"),
    new Letter("be", "べ"),
    new Letter("bo", "ぼ"),
    new Letter("pa", "ぱ"),
    new Letter("pi", "ぴ"),
    new Letter("pu", "ぷ"),
    new Letter("pe", "ぺ"),
    new Letter("po", "ぽ"),
    new Letter("ma", "ま"),
    new Letter("mi", "み"),
    new Letter("mu", "む"),
    new Letter("me", "め"),
    new Letter("mo", "も"),
    new Letter("ya", "や"),
    new Letter("yu", "ゆ"),
    new Letter("yo", "よ"),
    new Letter("ra", "ら"),
    new Letter("ri", "り"),
    new Letter("ru", "る"),
    new Letter("re", "れ"),
    new Letter("ro", "ろ"),
    new Letter("wa", "わ"),
    new Letter("wo", "を"),
    new Letter("n", "ん"),
]);

this_and_that = new Vocab("This and that", [
    new Word("this", "kore", "これ")
])

japanese = new Vocab("Japanese", [], [
    new Vocab("Writing", [], [hiragana]),
    new Vocab("Words", [], [this_and_that])
]);
japanese.chainLink("V");